### ISSUE TITLE
eval question 

### ISSUE THREAD

**Issue by YIFanH** [arthurchen0518/DirectionNet#3]
Hi, thanks for your work, i download code and run , load_sstable is not found error with data_loader.py,how i fix it ？

**Comment by arthurchen0518** [comment]
Sorry, load_sstable should be deprecated. It's fixed now. Thanks for spotting this.

**Comment by YIFanH** [comment]
@arthurchen0518  dose eval have to execute the process code with training process, the provided eval did not run successfully,my tf version is 2.8, and i update evaluation.evaluate_repeatedly to evaluation.evaluate_once is not work. i'm looking forward to your reply,thanks very mush
